config/routes.rb
Rails.application.routes.draw do
  root to: 'publications#index'

  resources :publications
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/publication.rb
class Publication < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController  
  before_action :set_publication, only: %i[update show destroy edit]
  def create 
    publication = Publication.create(publication_params)

    redirect_to publication_path(publication), notice: 'Вы создали блог!'
  end

  def update 
    @publication.update(publication_params)

    redirect_to publication_path(@publication), notice: 'Вы сохранили блог!'
  end

  def destroy 
    @publication.destroy

    redirect_to publication_path, notice: 'Вы удалили блог!'
  end

  def show
  end

  def index 
    @publication = Publication.all
  end

  def new 
    @publication = Publication.new
  end

  def edit 
  end

  private

  def publication_params 
    params.require(:publication).permit(:body, :post_title)
  end

  def set_publication 
    @publication = Publication.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogForUchi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <% if flash[:notice].present? %>
        <p class="mb mt message message-notice"><%= flash[:notice] %></p>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/publications/_form.html.erb
<%= form_with model: publication do |form| %>
  <p class="mb"><%= form.label :post_title, 'Название блога' %></p>
  <p class="mb"><%= form.text_field :body, class: 'form-text-area'  %></p>
  <p class="mb"><%= form.label :body, 'Текст блога'%></p>
  <p class="mb"><%= form.text_area :post_title, rows: 5, class: 'form-text-area'%></p>

  
  
  <p><%= form.submit 'Сохранить', class: 'button button-main' %></p>
<% end %>

app/views/publications/_publication.html.erb
<div class="mb-sm"> 
  <%= publication.body %>
</div>

<div class="text-sm publication-footer">
  <div class="text-gray"> 
    <%= l(publication.created_at, format: :short)%>
  </div>

  <div> 
    <%= link_to fa_icon('eye'), publication_path(publication), 
    method: :show, title: 'Открыть блог' %>
    <%= link_to fa_icon('pencil'), edit_publication_path(publication), 
      title: 'Редактировать блог' %>
    <%= button_to fa_icon('trash-o'), publication_path(publication), 
      method: :delete, title: 'Удалить блог' %>
  </div>
</div>



app/views/publications/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Редактировать блог <%= @publication.body %></h2>
  <%= render 'form', publication: @publication %>
</div>

app/views/publications/index.html.erb
<div class="container mb-sm">  
  <p>
    <%= link_to 'Написать новый блог', new_publication_path, class: 'button button-main' %>
  </p>
</div>

<div class="container">
  <h2 class="title-lg">Блоги</h2>  
</div>

<% @publication.each do |publication| %>
  <div class="mt-sm container">
    <%= render publication%>
  </div>
<% end %>

app/views/publications/new.html.erb
<div class="container">
  <h2 class="title-lg mb">Новый блог</h2>
  <%= render 'form', publication: @publication %>
</div>

app/views/publications/show.html.erb
<div class="container">

  <h2 class="title-lg_show mb"><%= render 'publication', publication: @publication %></h2>
  <%= @publication.post_title %>

  <p  class="mt"><%= link_to "Все блоги", publications_path %></p>
</div>